/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginpagecustomer;

import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class menuSelectionPage extends javax.swing.JFrame {
    public static String[]IDs;
    public static String[]taskNames;
    public static int[]taskNumbers;
    public static String[]developer;
    public static String[]descriptions;
    public static String[]taskStatus;
    public static int[]tasksDuration; 
    String numberOfTasks;
    int numOfTasks;
    String TaskName;
    String choice;
    int taskNumber = 0;
    String taskDescription;
    String FullName;
    String FirstName;
    String LastName;
    String expected;
    int expectedHour;
    String Status;
    String ID;
    int Hours = 0;
    /**
     * Creates new form menuSelectionPage
     */
    public menuSelectionPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOption1 = new javax.swing.JButton();
        btnOption2 = new javax.swing.JButton();
        btnOption3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setToolTipText("");

        btnOption1.setBackground(new java.awt.Color(204, 255, 255));
        btnOption1.setText("Option 1) Add Tasks");
        btnOption1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 153, 153), new java.awt.Color(255, 102, 102)));
        btnOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOption1ActionPerformed(evt);
            }
        });

        btnOption2.setBackground(new java.awt.Color(204, 204, 255));
        btnOption2.setText("Option 2) Show Report");
        btnOption2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), new java.awt.Color(255, 102, 102)));
        btnOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOption2ActionPerformed(evt);
            }
        });

        btnOption3.setBackground(new java.awt.Color(102, 153, 255));
        btnOption3.setText("Option 3) Exit             ");
        btnOption3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), new java.awt.Color(255, 102, 102)));
        btnOption3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOption3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MathJax_Math", 3, 24)); // NOI18N
        jLabel2.setText("Welcome To EasyKanban");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnOption1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOption3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOption2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 490, 480));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 1020, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOption1ActionPerformed
        // TODO add your handling code here:
  
                        numberOfTasks = JOptionPane.showInputDialog(null,"Please enter the number of tasks you wish to set: ","Add tasks",1);
                        numOfTasks = Integer.parseInt(numberOfTasks);
                        
                        taskNumbers = new int[numOfTasks];
                        taskNames = new String[numOfTasks];           
                        descriptions = new String[numOfTasks];
                        developer = new String[numOfTasks];
                        tasksDuration = new int[numOfTasks];
                        taskStatus = new String[numOfTasks]; 
                        IDs = new String[numOfTasks];
                        
            for(int i = 0; i < numOfTasks;i++){
                    TaskName = JOptionPane.showInputDialog(null,"Please enter the Task Name: ","Task Name",1);
                    taskNames[i] = TaskName;
                    taskNumber++;
                    taskNumbers[i]= taskNumber;
                    do{
                       taskDescription = JOptionPane.showInputDialog(null,"Please enter the Task Description, should not exceed over 50 characters: ","Task Description",1);
                    }while(!Methods.checkDescription(taskDescription));
                    
                    FirstName = JOptionPane.showInputDialog(null,"Please enter your First name: ","Developer Details",1);
                    LastName = JOptionPane.showInputDialog(null,"Please enter your Last name: ","Developer Details",1);
                    FullName = FirstName+" "+LastName;
                    developer[i]= FullName;
                    
                    expected = JOptionPane.showInputDialog(null,"Please enter your estimated duration for the task in hours: ","Task Duration",1);
                    expectedHour= Integer.parseInt(expected);
                    tasksDuration[i]= expectedHour;
                    
                    ID =  Methods.taskId(TaskName, taskNumber, FullName);
                    IDs[i] = ID;
                    
                    Status =  Methods.taskStatus();
                    taskStatus[i]= Status;
                    
                   Methods.printTaskDetails(Status, taskNumber, TaskName, taskDescription, ID, expectedHour, numOfTasks);
                   Hours = Hours + expectedHour;
                   
                   Methods.returnTotalHours(Hours); 
                }           
       
    }//GEN-LAST:event_btnOption1ActionPerformed

    private void btnOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOption2ActionPerformed
        // TODO add your handling code here:
do{
    choice = JOptionPane.showInputDialog(null,"Please select the following options:"
                + "\n1. Display all the tasks with the status of Done."
                + "\n2. Display the longest task duration."
                + "\n3. Search for a Task."
                + "\n4. Search for Tasks assigned to a developer"
                + "\n5. Delete a Task"
                + "\n6. Display a report of all captured Tasks."
                + "\n7. Go back to the Main Menu","Show Report", 1);
        
    switch(choice){

            case "1":
                Methods.displayTaskDone();
                    break;
            case "2":
                Methods.longestTaskDuration();
                    break;
            case "3":
                Methods.searchForTask();
                    break;
            case "4":
                Methods.developerTasks();
                    break;
            case "5":
                Methods.deleteTask(); 
                    break;
            case "6":
                Methods.displayTaskReport();
                    break;
            case "7": 
                    break;
            
        }
    }while(!choice.equals("7"));         
    }//GEN-LAST:event_btnOption2ActionPerformed

    private void btnOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOption3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thank you for using this Application, Goodbye!","Exit",1);
        System.exit(0);
    }//GEN-LAST:event_btnOption3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuSelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuSelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuSelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuSelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuSelectionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOption1;
    private javax.swing.JButton btnOption2;
    private javax.swing.JButton btnOption3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
